---

- name: 创建组
  group: name=mongodb
- name: 创建用户
  user: name=mongodb group=mongodb shell=/sbin/nologin

- name: 创建拷贝目录
  file: dest=/usr/local/src/mongodb3.6.9 state=directory
  file: dest=/usr/local/mongodb state=directory  
                    
- name: 发送mongodb文件到远程主机
  copy: "src={{ item.src }} dest={{ item.dest }}"
  with_items: 
      - src: "/etc/ansible/roles/mongodb/files/mongodb3.6.9/mongodb-linux-x86_64-rhel70-3.6.9.tgz"
        dest: "/usr/local/src/mongodb3.6.9"

- name: 安装依赖包
  shell: yum -y install gcc* make cmake autoconf libtool 

- name: 编译安装mongodb
  shell: 
       cd /usr/local/src/mongodb3.6.9;tar -zxvf mongodb-linux-x86_64-rhel70-3.6.9.tgz -C /usr/local/mongodb;mkdir -pv /usr/local/mongodb/mongodb-linux-x86_64-rhel70-3.6.9/{data,logs};

- name: 加入二进制程序
  shell:
       echo 'export PATH=/usr/local/mongodb/mongodb-linux-x86_64-rhel70-3.6.9/bin/:/usr/local/mongodb/mongodb-linux-x86_64-rhel70-3.6.9/sbin:$PATH' >> /etc/profile.d/mongodb.sh;

- name: 拷贝配置文件mongodb.conf
  copy: src=/etc/ansible/roles/mongodb/files/mongodb3.6.9/mongodb.conf dest=/usr/local/mongodb/mongodb-linux-x86_64-rhel70-3.6.9/mongodb.conf
  
- name: 优化了系统参数
  shell:
       sed -i 's|#DefaultLimitNOFILE=|DefaultLimitNOFILE=32000|' /etc/systemd/system.conf;sed -i 's|#DefaultLimitNPROC=|DefaultLimitNPROC=32000|' /etc/systemd/system.conf;

- name: 安装mongodb启动脚本
  copy: src=/etc/ansible/roles/mongodb/files/mongodb3.6.9/mongodb.service dest=/usr/lib/systemd/system/mongodb.service mode=0755

- name: 赋予解压目录用户
  file: path=/usr/local/mongodb owner=mongodb group=mongodb state=directory recurse=yes


- name: 开启mongod
  service: name=mongodb state=started enabled=yes

- name: 开放端口服务
  shell:
      firewall-cmd --permanent --zone=public --add-port=27017/tcp --permanent;
      firewall-cmd --permanent --query-port=27017/tcp;
      firewall-cmd --reload;
